### ISSUE TITLE
Start embed Cassandra from SBT

### ISSUE THREAD

**Issue by fedefernandez** [frees-io/freestyle-cassandra#88]
In order to test the interpolator, we need a Cassandra instance running before the test compilation. In this way, one approach could be to start and stop the Cassandra instance from SBT.

Also, finish the test `MetadataInterpolatorTest` in `macros-tests` project.

**Comment by fedefernandez** [comment]
Stopping Cassandra in `afterAll` also gives the following error:
```bash
Exception in thread "Thread-19" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2608)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:809)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:798)
	at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 21 seconds, 291 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 4, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error: Total 3, Failed 0, Errors 0, Passed 3
[error] Error during tests:
[error] 	Forked test harness failed: java.io.EOFException
[error] 	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2608)
[error] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
[error] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
[error] 	at sbt.React.react(ForkTests.scala:156)
[error] 	at sbt.ForkTests$Acceptor$2$.run(ForkTests.scala:96)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (macros-tests/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 25 s, completed Oct 10, 2017 5:55:36 AM
```

**Comment by fedefernandez** [comment]
Also, the tests using Cassandra should be created as integration tests
